version: '3.1'
services:
  app:
    container_name: stockanalyzer-app
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    env_file:
      - ./config_credentials/docker.env
    environment:
      TZ: Europe/Warsaw
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      spring_profiles_active: prod
    volumes:
      - ./stockanalyzer-github-release.jar:/app-build/stockanalyzer-prod.jar
    networks:
      - stockanalyzer-network
    entrypoint: java -jar /app-build/stockanalyzer-prod.jar

networks:
  stockanalyzer-network:
    external: true
