version: '3.1'

services:
  mongo:
    container_name: stockanalyzer-mongodb
    image: mongo
    restart: always
    ports:
      - 27018:27017
    env_file:
      - ./config_credentials/docker.env
    networks:
      - stockanalyzer-network
    volumes:
      - ./.docker-volumes/mongodb:/data/db

networks:
  stockanalyzer-network:
    external: true