analyzer:
  title: Hello
  limit: 10

stock-api:
  url: ${GPW_API_URL}

twitter-config:
  apiKey: ${TWITTER_apiKey}
  apiSecretKey: ${TWITTER_apiSecretKey}
  accessToken: ${TWITTER_accessToken}
  accessTokenSecret: ${TWITTER_accessTokenSecret}

spring:
  data:
    mongodb:
      uri: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27018}/"
      database: "stockanalyzer"
  mustache:
    suffix: .html

logging:
  level.root: WARN
  level.pl.slaszu: DEBUG