analyzer:
  title: Hello
  limit: 10

stock-api:
  url: https://gpw.g-sitemap-generator.com


spring:
  data:
    mongodb:
      uri: "mongodb://root:example@localhost:27017/"
      database: "stockanalyzer"