analyzer:
  title: Hello
  limit: 10

stock-api:
  url: https://gpw.g-sitemap-generator.com

twitter-config:
  credentialsFile: '/config_credentials/twitter.json'

spring:
  data:
    mongodb:
      uri: "mongodb://root:example@localhost:27018/"
      database: "stockanalyzer"

logging:
  level.root: WARN
  level.pl.slaszu: DEBUG