analyzer:
  title: Hello
  limit: 10

stock-api:
  url: ${GPW_API_URL}

twitter-config:
  apiKey: ${TWITTER_apiKey}
  apiSecretKey: ${TWITTER_apiSecretKey}
  accessToken: ${TWITTER_accessToken}
  accessTokenSecret: ${TWITTER_accessTokenSecret}

qdrant:
  apiKey: ${QDRANT_KEY}
  collectionName: gpw_api_signals_test

blogger-google-api-oauth:
  tokenStorageDir: ${DOCKER_CONFIG_CREDENTIALS_DIR}/blogger-stored-token/
  credentialFileJson: ${DOCKER_CONFIG_CREDENTIALS_DIR}/blogger-credential.json
  blogId: "2989806055464746341"


spring:
  data:
    mongodb:
      uri: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27018}/"
      database: "stockanalyzer"
  mustache:
    suffix: .html
  task:
    scheduling.pool.size: 10

logging:
  level.root: WARN
  level.pl.slaszu: DEBUG

sentry:
  dsn: https://91448fb4cf34aae51004514cd4526af3@o74341.ingest.us.sentry.io/4507126154657792
  tracesSampleRate: 1.0